name: Build rc4_encryptor for ImmortalWrt

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 步骤1: 检出你的代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤2: 安装依赖并下载、解压 SDK
      - name: Setup SDK
        run: |
          sudo apt-get update && sudo apt-get install -y zstd
          SDK_URL="https://downloads.immortalwrt.org/releases/24.10.2/targets/ramips/mt7620/immortalwrt-sdk-24.10.2-ramips-mt7620_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
          SDK_FILE="immortalwrt-sdk.tar.zst"
          curl -Lfo $SDK_FILE "$SDK_URL"
          if [ ! -s "$SDK_FILE" ]; then
            echo "::error::SDK download failed or the file is empty."
            exit 1
          fi
          mkdir sdk
          tar -I zstd -xf $SDK_FILE -C sdk --strip-components=1
          echo "SDK extracted successfully."

      # 步骤3: 编译 C 代码 (已修正查找编译器的方法)
      - name: Compile rc4_encryptor
        run: |
          # 使用 find 命令来安全地查找编译器，避免 grep 的解析问题
          # -type f: 只查找文件
          # -name '*-gcc': 查找以 -gcc 结尾的文件
          # -print -quit: 找到第一个匹配项后就打印并退出
          CC=$(find sdk/staging_dir/toolchain-*/bin -type f -name '*-gcc' -print -quit)
          
          if [ -z "$CC" ]; then
            echo "::error::Cross-compiler not found!"
            exit 1
          fi

          echo "Using compiler: $CC"
          
          # 执行编译
          $CC rc4.c -o rc4_encryptor -static
          
          echo "Compilation finished."
          ls -l rc4_encryptor

      # 步骤4: 上传构建产物
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rc4_encryptor_mipsel_24kc
          path: rc4_encryptor
